version: '3'
services:
  redis-rdb:
    container_name: "redis-rdb"
    image: redis:6-alpine
    command: redis-server --appendonly no --port 6379 --dir /var/redis --dbfilename dump.rdb
    volumes:
      - ./config/redis/rdb/data:/var/redis
    ports:
      - "6379:6379"
  redis-aof:
    container_name: "redis-aof"
    image: redis:6-alpine
    command: redis-server --appendonly yes --save "" --port 6378
    ports:
      - "6378:6378"
  redis-aof-rdb:
    container_name: "redis-aof-rdb"
    image: redis:6-alpine
    command: redis-server --appendonly yes --port 6377
    ports:
      - "6377:6377"
  beanstalkd:
    container_name: "beanstalkd"
    image: schickling/beanstalkd
    ports:
      - "11300:11300"
#volumes:
#  - redis_rdb_data: {}
#  - redis_aof_data: {}
#  - redis_aof_rdb_data: {}